esphome:
  name: mobilestation
# Example configuration entry
esp32:
  board: nodemcu-32s
# Network Settings
wifi:
  ssid: WLAN_MN
  password: b952516391da733f5f5a13b717
logger:
  level: DEBUG
ota:
  safe_mode: true
  password: ma3400nau
# MQTT Settings
mqtt:
  broker: 10.1.0.2
dallas:
  - pin: GPIO23
    update_interval: 30s
# Example configuration entry with 2 sensors and filter
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: dallas
    address: 0x3601203325ae3028
    name: "Temp1"
  - platform: dallas
    address: 0x72012032b527b428
    name: "Temp2"
  - platform: dallas
    address: 0x7e3ce104576ff028
    name: "Temp3"
  - platform: dallas
    address: 0x7e3ce1045751ec28
    name: "Temp4"
  - platform: dallas
    address: 0x1e3ce104570f9628
    name: "Temp5"
  - platform: dallas
    address: 0x6e3ce104571dce28
    name: "Temp6"
  - platform: dallas
    address: 0xcb3ce10457ec4128
    name: "Temp7"
  - platform: dallas
    address: 0x953ce10457ba3b28
    name: "Temp8"